/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package banking.project;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class BankingApp {
    private Bank bank;
    private Map<String, Account> accounts;
    private Scanner scanner;

    public BankingApp() {
        bank = new Bank();
        accounts = new HashMap<>();
        scanner = new Scanner(System.in);
    }
    
    public void run() {
        Account account1 = new Account("1234", "Starry Sky");
        Account account2 = new Account("5678", "Yellow Sun");
    }

    bank.addAccount(account1);
    bank.addAccount(account2);

    boolean running = true;
    while(running)
    {
        displayMenu();
        int userChoice = scanner.nextInt();
        scanner.nextLine();
        if (userChoice == 1) {
            displayAccounts();
        }else if (userChoice == 2) {
            makeDeposit();
        } else if (userChoice == 3) {
            makeWithdrawl();
        } else if (userChoice == 4) {
            checkBalance();
        } else if (userChoice == 5) {
            closeAccount();
        } else if (userChoice == 6) {
            running = false;
        } else {
            System.out.println("This is not a valid choice. Please make another selection.");
        }
    }

    




















}
