/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package banking.project;

public class App {
    
    import java.util.Collection;
import java.util.HashMap;
public class Bank {
    HashMap<String, Account> accounts = new HashMap<>();
    public Collection<Account> getAllAccounts() {
        return accounts.values();
    }
    public void addAccount(Account accountToAdd) {
        accounts.put(accountToAdd.getAccountNumber(), accountToAdd);
    }
}
}











Message Luke Moore










}
