/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package banking.project;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class BankingApp {
    private Bank bank;
    private Map<String, Account> accounts;
    private Scanner scanner;

    public BankingApp() {
        bank = new Bank();
        accounts = new HashMap<>();
        scanner = new Scanner(System.in);
    }
    


    




















}
